server:
  port: 8082
spring:

  #通用的的数据源配置。
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TempCOIN?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jy666233
  jpa:
    hibernate:
      ddl-auto: update
